### ISSUE TITLE
Specs require that the User's name and the Tag's name is unique.

### ISSUE THREAD

**Issue by azheng249** [learn-co-students/rails-blog-associations-validations-v-000#36]
Inside the spec helper, a user called "Crookshanks" and tags called "adorable"  and "cute" are created. The specs for user and tag uniqueness conflict with the specs in the following specs:

/01_models/01_user_spec.rb - line 18
    let(:user) { User.create(name: 'Crookshanks') }
/01_models/02_post_spec.rb - line 17,18
    let(:user) { User.create(name: 'Crookshanks') }
    let(:tag1) { Tag.create(name: 'adorable') }
/01_models/03_tag_spec.rb - line 14
    let(:tag) { Tag.create(name: 'cute') }

Before every test, those users and tags are already created. Because of the uniqueness validation, it would render those users and tags invalid and not be created properly, which would the specs to fail.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
