### ISSUE TITLE
Curriculum is out of order

### ISSUE THREAD

**Issue by squirrelnest** [learn-co-students/rails-blog-associations-validations-v-000#418]
This lab should appear after the Active Record Associations Review lesson.

**Comment by DakotaLMartinez** [comment]
agreed. This lesson should not come before has_many, through has been introduced.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
